{
 "title": "NVIDIA/DCGM/Exporter/Container",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": "label_values(DCGM_FI_DEV_GPU_UTIL, exported_namespace)"
   },
   {
    "name": "pod",
    "query": "label_values(DCGM_FI_DEV_GPU_UTIL{exported_namespace=\"$namespace\"}, exported_pod)"
   },
   {
    "name": "container",
    "query": "label_values(DCGM_FI_DEV_GPU_UTIL{exported_namespace=\"$namespace\",exported_pod=\"$pod\"}, exported_container)"
   }
  ]
 },
 "panels": [
  {
   "title": "GPU Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_DEV_GPU_UTIL{exported_namespace=\"$namespace\",exported_pod=\"$pod\",exported_container=\"$container\"}",
     "legendFormat": "{{exported_pod}}"
    }
   ]
  },
  {
   "title": "GPU Framebuffer Mem",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_DEV_FB_USED{exported_namespace=\"$namespace\",exported_pod=\"$pod\",exported_container=\"$container\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "DCGM_FI_DEV_FB_FREE{exported_namespace=\"$namespace\",exported_pod=\"$pod\",exported_container=\"$container\"}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "GPU Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_DEV_FB_USED{exported_namespace=\"$namespace\",exported_pod=\"$pod\",exported_container=\"$container\"}*100/DCGM_FI_DEV_FB_FREE{exported_namespace=\"$namespace\",exported_pod=\"$pod\",exported_container=\"$container\"}",
     "legendFormat": "{{exported_pod}}"
    }
   ]
  }
 ]
}