apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: uk8s-prometheus
    chart: uk8s-prometheus-1.0.10
    k8s-app: uk8s-monitor
    release: uk8s-monitor
  name: uk8s-dcgm
  namespace: uk8s-monitor
spec:
  groups:
  - name: gpu
    rules:
    - alert: gpuXidError
      annotations:
        message: GPU {{ $labels.device }} on host {{ $labels.Hostname }} has reported
          xid error {{ $value }}
      expr: DCGM_FI_DEV_XID_ERRORS > 0
      for: 1m
      labels:
        severity: critical