apiVersion: v1
kind: ServiceAccount
metadata:
  name: cni-vpc-ipamd
  namespace: kube-system
  labels:
    app: "cni-vpc-ipamd"
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cni-vpc-ipamd
  labels:
    app: "cni-vpc-ipamd"
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get","list", "update"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get"]
- apiGroups: ["vpc.uk8s.ucloud.cn"]
  resources: ["vpcipclaims", "ipamds"]
  verbs: ["get", "create","delete","update","list"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cni-vpc-ipamd
  labels:
    app: "cni-vpc-ipamd"
subjects:
  - kind: ServiceAccount
    name: cni-vpc-ipamd
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: cni-vpc-ipamd
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cni-vpc-ipamd
  namespace: kube-system
  labels:
    app: "cni-vpc-ipamd"
spec:
  selector:
    matchLabels:
      app: "cni-vpc-ipamd"
  template:
    metadata:
      labels:
         app: "cni-vpc-ipamd"
    spec:
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - key: dedicated
        operator: Exists
      - effect: NoSchedule
        key: node.cloudprovider.kubernetes.io/uninitialized
        value: "true"
      serviceAccount: cni-vpc-ipamd
      hostNetwork: true
      priorityClassName: system-node-critical
      hostPID: true
      containers:
        - name: cni-vpc-ipamd
          image: uhub.service.ucloud.cn/uk8s/cni-vpc-ipamd:1.0.1
          resources:
            limits:
              cpu: 200m
              memory: 512Mi
            requests:
              cpu: 200m
              memory: 512Mi
          securityContext:
            privileged: true
          args:
            - "--availablePodIPLowWatermark=3"
            - "--availablePodIPHighWatermark=50"
            - "--calicoPolicyFlag=true"
            - "--cooldownPeriodSeconds=30"
          imagePullPolicy: "Always"
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "rm -rf /run/cni-vpc-ipamd.sock"]
          envFrom:
          - configMapRef:
              name: uk8sconfig
          env:
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: user-config
              mountPath: /etc/uk8s/
            - name: host-run
              mountPath: /run/
            - name: host-log
              mountPath: /var/log/ucloud/
            - name: host-cni
              mountPath: /opt/cni/
            - name: device-plugin-path
              mountPath: /var/lib/kubelet/device-plugins
            - name: var-run-ns
              mountPath: /var/run/netns/
              mountPropagation: "Bidirectional"
            - name: host-data
              mountPath: /etc/kubernetes
              readOnly: true
      volumes:
        - name: host-run
          hostPath:
            path: /run/
        - name: host-log
          hostPath:
            path: /var/log/ucloud/
        - name: device-plugin-path
          hostPath:
            path: /var/lib/kubelet/device-plugins
            type: "Directory"
        - name: var-run-ns
          hostPath:
            path: /var/run/netns/
        - name: host-cni
          hostPath:
            path: /opt/cni/
        - name: user-config
          configMap:
            name: uk8sconfig
        - name: host-data
          hostPath:
            path: /etc/kubernetes
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: ipamds.vpc.uk8s.ucloud.cn
spec:
  group: vpc.uk8s.ucloud.cn
  versions:
    - name: v1beta1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                node:
                  type: string
                addr:
                  type: string
                subnet:
                  type: string
            status:
              type: object
              properties:
                current:
                  type: integer
                high:
                  type: integer
                low:
                  type: integer
                status:
                  type: string
  scope: Namespaced
  names:
    plural: ipamds
    singular: ipamd
    kind: Ipamd

